name: deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: ./docker.sh  

      - name: Install Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo systemctl status apache2 || true  # Check status, but ignore errors for workflow

      - name: Create a new directory
        run: mkdir -p classwork

      - name: Create a new text file and add content
        run: echo "my name is masturah" > classwork/inventory.txt



