name: deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y curl
          curl -fsSL https://get.docker.com
          curl -fsSL https://get.docker.com | sudo sh
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Create a new directory
        run: mkdir -p classwork

      - name: Create a new text file and add content
        run: echo "my name is masturah" > classwork/inventory.txt



